# Fix Option+Backspace to delete whole word
set -g default-terminal "screen-256color"
set -as terminal-overrides ',*:kbs=\177'
bind-key -n M-BSpace send-keys M-BSpace

# Set terminal tab title to session name
set -g set-titles on
set -g set-titles-string '#S'

# Mouse support
set -g mouse on

# macOS-style copy with mouse selection
set -g set-clipboard on
bind -T copy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"
